### ISSUE TITLE
How to improve F rating from CryptCheck?

### ISSUE THREAD

**Issue by tswast** [JrCs/docker-letsencrypt-nginx-proxy-companion#197]
My domain is getting an [F rating from CryptCheck](https://tls.imirhil.fr/https/dev.timswast.com) when I use this set up.

I believe the main source of the bad rating is the use of [CBC](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_.28CBC.29) instead of [GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode).

Maybe this container could use a more [hardened NGINX SSL configuration](https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html) by default?

Is there a way to customize it in the meantime?

**Comment by buchdag** [comment]
The SSL configuration is mostly provided by the nginx.tmpl file so this issue is more immediately relevant to [jwilder/nginx-proxy](../../../jwilder/nginx-proxy) than it is to this project.

The F rating from CryptCheck is mostly due to [TLSv1 and TLSv1.1 support](../../../jwilder/nginx-proxy/blob/master/nginx.tmpl#L180). Remove them from the nginx.tmpl you're using and you'll obtain an A on CryptCheck.

For an A+ you'll need to remove the ciphers that do not permit Perfect Forward Secrecy from the next line, namely:

AES256-GCM-SHA384
AES256-SHA
AES256-SHA256
AES128-GCM-SHA256
AES128-SHA
AES128-SHA256

**Comment by buchdag** [comment]
You can now do this in an easier way if you use the latest version of [nginx.tmpl](https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl): juste add the environment variable `SSL_POLICY` set to `Mozilla-Modern` to your proxyed container(s).
