### ISSUE TITLE
failed to create cert because letsencrypt container can't reach the local site

### ISSUE THREAD

**Issue by Robin2009** [JrCs/docker-letsencrypt-nginx-proxy-companion#207]
I'm trying to set up a nginx-proxy + docker-letsencrypt-nginx-proxy-companion to proxy my test web app which's also running as a container, simply like that. Here's my scripts:
```
#step1: start up the reverse-proxy:
docker run -d -p 80:80 -p 443:443 \
    --name nginx-proxy \
    -v $PWD/certs:/etc/nginx/certs:ro \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true \
    jwilder/nginx-proxy

#step2: start up the letsencrypt-nginx-proxy
docker run -d \
    --name nginx-letsencrypt \
    --volumes-from nginx-proxy \
    -v $PWD/certs:/etc/nginx/certs:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion

#step3: start up my test web app
docker run -d \
    --name site-a \
    -e 'LETSENCRYPT_EMAIL=shenpan2009@gmail.com' \
    -e 'LETSENCRYPT_HOST=my.test.com' \
    -e 'VIRTUAL_HOST=my.test.com' training/webapp
```
I had already put `127.0.0.1 my.test.com` into the `/etc/hsots` on my mac. The things is, after its executed I can only access the test web from http://my.test.com, and the logs of `nginx-letsencrypt` told me this service `was not able to reach http://my.test.com/.well-known/acme-challenge/xngtTPnXmC-s__eWccp64NEDvPxJshsvjpob-9Key3w: HTTPConnectionPo
ol(host='my.test.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/xngtTPnXmC-s__eWccp64NEDvPxJshsvjpob-9Key3w (Caused by NewConnectionError('<reques
ts.packages.urllib3.connection.HTTPConnection object at 0x7f8575a16210>: Failed to establish a new connection: [Errno 111] Connection refused',))`. 

Well, I'm not sure if it's because the `nginx-letsencrypt` can't recognize the domain name 'my.test.com' specified by its host machine, however, after bash into the `nginx-letsencrypt`, I could ping to this domain even though `curl http://my.test.com` returns me a same error saying 'connection refused'. So someone please kindly give me any suggestion to get it work...thanks!

**Comment by lounagen** [comment]
@Robin2009: this project is intended to format and send certificate requests to the Letsencrypt CA registration endpoint, and does NOT create ssl certificates from local.

So, your domain must be valid and resolved from the LE pool of servers  (a.k.a. from the whole externat Internet network, and not 127.0.0.1).

Regarding your bash test inside the nginx-letsencrypt container, if you put an ip into your host's etc/hosts (here, your mac os), it won't be 'copied' to your docker container, which will use its own network rules to connect this ip (you could use a dnsmask+--dns option on the host to do this or the --add-host option).
Btw, even if you forward the my.test.com 127.0.0.1 rule to your containers, you could not see any running service from the container's localhost.

Shortly said: buy a valid domain or use a local CA instead of this letsencrypt stuff

**Comment by Robin2009** [comment]
@lounagen Sorry for my late reply, and that's a great explanation! Thanks so much

**Comment by opyate** [comment]
@Robin2009 if you already own a domain and use Cloudflare, I've got a nice working example for you here: https://github.com/opyate/docker-letsencrypt-nginx-proxy-companion
