### ISSUE TITLE
Feature Request: Ability to specify custom name of key file (other than key.pem)

### ISSUE THREAD

**Issue by mjlongfl** [JrCs/docker-letsencrypt-nginx-proxy-companion#313]
I would like to request the ability to specify a custom name for the various certificate-related files, specifically, the key file (key.pem).

I use this container with another container ([jacobalberty/unifi](https://hub.docker.com/r/jacobalberty/unifi/)) that expects the key file name to be privatekey.pem.

Thank you for providing a great container to make using Let's Encrypt certificates so easy!

**Comment by buchdag** [comment]
Hi,

First, the name of the key file (`key.pem`) is hardcoded inside the ACME client we're using, [`simp_le`](https://github.com/zenhack/simp_le). The project manifesto state that specifying output file paths is not allowed by design (don't ask me why, I'm not the original creator) and that user should symlink if necessary. That's precisely what `letsencrypt-nginx-proxy-companion` does to have automated working setups with `nginx-proxy`.

We could add that kind of feature but I think that's tangent to #275, as in the end goal make sense to me but is out of the stated scope of the current project (automated cert creation for nginx-proxy). I'm not saying that won't be done ever but I think there is still a lot of work to do on the core functionality and that jury rigging out of scope features right now might not be a good long term idea.

**Comment by buchdag** [comment]
And I can help you jury rigg this feature into a forked version if you'd like.

**Comment by mjlongfl** [comment]
Thank you for the feedback. I did not realize that `simp_le` required the key to be named a certain way (I saw the file being passed as an argument to `simp_le`, therefore, I thought it would be a simple change).

I guess this issue is related to #275 in a way because the third-party application is not using the nginx proxy to provide the secure connection.

At this time, I did (manually) create a soft-link to provide the appropriate key file naming the third-party application expects. However, that soft-link will be destroyed once the certificate is renewed (because this container recreates (removes then creates) the entire directory instead of replacing the files within the directory).

Without creating a fork, I saw 3 options:
1. Ask the third-party application to allow for a custom name for the key file
2. Ask this project to allow for a custom name for the key file
3. Ask this project to introduce configurable event hooks (a la [CertBot](https://certbot.eff.org/))

I figured option 2 was the simplest request and would provide benefit to the community (and I now understand why it cannot be done). I believe option 3 would provide the most benefit to the community but I figured that was a more significant request.

I understand that I could always go the fork route but I thought that there could be benefit to the community with a minor change.

Again, thanks for your feedback and thanks again for a great project.
