### ISSUE TITLE
Possible to hide/change/close port 80?

### ISSUE THREAD

**Issue by hvorragend** [JrCs/docker-letsencrypt-nginx-proxy-companion#322]
I use the variant with the separate containers, as recommended in the wiki.
Everything is fine. I can access my servers on port 443.
But there is still the port 80 open and I wonder if that's a security problem.
I am getting the message "503 Service Temporarily Unavailable" on my port 80 site.
I know that we have to open/forward the port 80 for letsencrypt.
But is it possible to hide/close/change the default port 80?
Can I use a basic authentification for this port? But is the certificate cronjob working after that?
Thank you.

**Comment by buchdag** [comment]
Hi.

The fact that port 80 has to be opened does not introduce security problem(s).

Using the default nginx.tmpl, with no additional nginx-proxy configuration, when you send an http request to the port 80, either one of those things happen:

- the hostname sent by the client correspond to a domain that's currently configured on the proxy and ssl is not configured for this domain : the request is forwarded to the corresponding container.
- the hostname sent by the client correspond to a domain that's currently configured on the proxy and ssl is configured for this domain : the request is redirected to port 443 and forwarded to the corresponding container.
- the hostname sent by the client does not correspond to a domain that's currently configured on the proxy : nginx answer with a 503 error.

You can't close or change the port 80 or `http-01` challenges will fail. There isn't really a way to "hide" a port, either it is open and will answer / shows up on scan, or it's closed. Reasons why you can't filter either are described here : https://community.letsencrypt.org/t/ip-addresses-le-is-validating-from-to-build-firewall-rule/5410/22

Authentication is not a concept related to a port, the web servers that get request forwarded to them ask for authentication, not the proxy. Authentication is disabled for the challenge folder anyway, because as you guessed that would prevent the validation server from accessing the file.

**Comment by hvorragend** [comment]
Thank you for this detailed and very helpful answer. 
You helped me a lot and calmed me down. :-)

> the hostname sent by the client does not correspond to a domain that's currently configured on the proxy : nginx answer with a 503 error.

That one is my problem. 
I'll think a little bit about whether or not to disable the other domains.
I have three domains (CNAME redirect) pointing to a dynamic IP.

**Comment by buchdag** [comment]
If the 503 is bothering you, you can use nginx-proxy [`DEFAULT_HOST`](https://github.com/jwilder/nginx-proxy#default-host) environment variable.

**Comment by hvorragend** [comment]
Thank you very much.

I am using the separate containers-method, so I don't have a nginx-proxy container (official nginx instead). So I added the DEFAULT_HOST do the nginx-gen-container and it seems to work.

**Comment by buchdag** [comment]
Yes, nginx-proxy environment variables have to be set on the docker-gen container when you use the three containers setup.
