### ISSUE TITLE
Unable to make http call from within container

### ISSUE THREAD

**Issue by negamaxi** [JrCs/docker-letsencrypt-nginx-proxy-companion#324]
Hi there. I have a nodejs container with http server behind letsencrypt-nginx-proxy network. I am able to make requests to the server from outside (my browser for instance), but for some reason I'am unable to make same requests from within containers.

```bash
# inside nodejs container with app
curl http://mywebsite.com/api?param=value
```
It takes some minutes to throw an error:

```bash
curl: (7) Failed to connect to mywebsite.com port 80: Connection timed out
```
`ping mywebsite.com` works well. Am I missing something?

PS: I am trying to make call to the same app that launched insde nodejs container.
PPS: https doesn't work as well
PPPS: use localhost is not an option, calls must be made using domain name.

**Comment by buchdag** [comment]
Just tried without issue on two containers, one based on alpine (nginx:alpine) and another based on debian.

The container based on alpine resolve its domain name to its own IP because hostname and domainname were set on its compose file.

The container based on debian resolve its domain name to the public IP of the docker host.

**Comment by negamaxi** [comment]
Found a workaround that works fine for me, still have no idea why issue appeared though.
