### ISSUE TITLE
create temp file

### ISSUE THREAD

**Issue by PhiGi87** [JrCs/docker-letsencrypt-nginx-proxy-companion#340]
Hi, 

I'll make it short: I want to test it and I get the following error on nginx-gen:
`2018/03/02 08:26:09 Cnable to create temp file: open /etc/nginx/conf.d/docker-gen648754996: no such file or directory
`
i start the container with this:

> docker run -d \
>   --name nginx-gen \
>   --volumes-from nginx-proxy \
>   -v /home/cloud-host/conf/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
>   -v /var/run/docker.sock:/tmp/docker.sock:ro \
>   --label com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen \
>   jwilder/docker-gen \
>   -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
> 
> docker run -d -p 80:80 -p 443:443 \
>   --name nginx-proxy \
>   -v /home/cloud-host/certs:/etc/nginx/certs:ro \
>   -v /etc/nginx/vhost.d \
>   -v /usr/share/nginx/html \
>   -v /var/run/docker.sock:/tmp/docker.sock:ro \
>   --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
>   jwilder/nginx-proxy
>   
> docker run -d \
>   --name nginx-letsencrypt \
>   --volumes-from nginx-proxy \
>   -v /home/cloud-host/certs:/etc/nginx/certs:rw \
>   -v /var/run/docker.sock:/var/run/docker.sock:ro \
>    -e NGINX_DOCKER_GEN_CONTAINER=nginx-gen \
>    -e NGINX_PROXY_CONTAINER=nginx-proxy \
>   jrcs/letsencrypt-nginx-proxy-companion

Can someone help me? I'm a little bit surprised. :-) Thanks

**Comment by buchdag** [comment]
Hi. The two setups are either:

- nginx-proxy + le-companion
- nginx (not nginx-proxy)  + docker-gen + le-companion

nginx-proxy + docker-gen + le-companion is an erroneous setup.

If you want to use the three containers setup, as explained in the doc you have to share the `/etc/nginx/conf.d` folder between the nginx and docker-gen containers with a docker volume.

That's what your docker-gen container is complaining about, it can't write to `/etc/nginx/conf.d` because it did not get this volume / folder from the nginx container.

I'd suggest that you check https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Advanced-usage
