### ISSUE TITLE
Hook to restart container or service after renewal

### ISSUE THREAD

**Issue by lukecyca** [JrCs/docker-letsencrypt-nginx-proxy-companion#415]
I am using certificates generated by letsencrypt-nginx-proxy-companion for a Mosquitto server running on the same machine in another container. This server runs on a different port, using a hostname that is also used for a web app via nginx-proxy. Hence it is convenient to just reuse the same certificate that is being generated for the latter.

The problem is when the certificate is renewed, the Mosquitto server doesn't know to reload the cert. Is there a way I could have letsencrypt-nginx-proxy-companion restart an arbitrary container when a cert is renewed?

**Comment by buchdag** [comment]
> Is there a way I could have letsencrypt-nginx-proxy-companion restart an arbitrary container when a cert is renewed?

Unfortunately no and I don't think this will be added, because this is a bit too far from the original scope (automate creation and renewal of LE certificate for use with nginx-proxy, which assume that nginx-proxy acts as an SSL termination proxy).

That might be doable using some combination of inotify and the docker API but I won't be of much help if you want to try this.

**Comment by lukecyca** [comment]
Understandable. I may try to implement this using inotify/docker API as you suggest. Or even just a daily cron job to restart the container iff the cert files on disk are < 24 hours old.
