### ISSUE TITLE
SSL Issuer shows container name

### ISSUE THREAD

**Issue by skiedude** [JrCs/docker-letsencrypt-nginx-proxy-companion#490]
Wondering what I've done wrong. When I run the cert_status script inside the nginx-proxy-companion container I see the following
` 
/etc/nginx/certs/sub.domain.com/fullchain.pem: OK
Certificate was issued by Let's Encrypt Authority X3
Certificate is valid until Apr  4 21:32:51 2019 GMT
Subject Name:
- sub.domain.com
Certificate is used by the following domain(s):
- sub.domain.com
`

Which looks like a normal LetsEncrypt SSL that expires in 90 days. However when I inspect the SSL from my computer, or try to visit it via browser, I get a ERR_CERT_AUTHORITY_INVALID and see the following:
`    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=letsencrypt-nginx-proxy-companion
        Validity
            Not Before: Jan  4 22:17:44 2019 GMT
            Not After : Jan  4 22:17:44 2020 GMT
        Subject: CN=letsencrypt-nginx-proxy-companion`

Am I misunderstanding how this container works in requesting a valid LetsEncrypt SSL?

Thanks!

**Comment by skiedude** [comment]
Also of note, I'm attempting to setup https://github.com/algolia/sup3rS3cretMes5age which attempts to self congiure nginx-proxy-companion.

**Comment by buchdag** [comment]
Hi. Sorry but we can't provide support for third party implementation of this project.

The certificate with `CN=letsencrypt-nginx-proxy-companion` is [the default certificate that get created on container startup](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/entrypoint.sh#L97). If you hit the default certificate instead of your service's cert, that probably means the proxy is not configured properly. No idea why.

Please open an issue directly on the [`algolia/sup3rS3cretMes5age`](https://github.com/algolia/sup3rS3cretMes5age) repository if you need further help.
