### ISSUE TITLE
Add global variable for default LETSENCRYPT_EMAIL

### ISSUE THREAD

**Issue by jeroen-plug** [JrCs/docker-letsencrypt-nginx-proxy-companion#525]
All of the containers I use nginx-proxy for are using the same value for LETSENCRYPT_EMAIL. It would be cool if I could set a default for this value, by setting an environment variable on the letsencrypt container.

**Comment by buchdag** [comment]
Well, this is not documented yet but I realised a few month ago that `LETSENCRYPT_EMAIL` does not work as it should anyway : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/510#issuecomment-463256716

The real behaviour is that the first `LETSENCRYPT_EMAIL` environment variable you set will become the default address, and subsequent `LETSENCRYPT_EMAIL` environment variables, wether they're set or not and different or not won't have any effect, providing you use the same ACME account for all of those containers. Email addresses are by ACME account, not by certificate issuance.

I've lacked time lately to address this.

**Comment by buchdag** [comment]
I'm currently working on this feature and on a modification to the doc that explains why the base `LETSENCRYPT_EMAIL` feature does not work as intended, how it works in practice, and what can be done to make it work as intended.

Here is the WIP doc modification, advice would be welcome:

#### Contact address

The `LETSENCRYPT_EMAIL` environment variable must be a valid email and will be used by Let's Encrypt to warn you of impeding certificate expiration (should the automated renewal fail) and to recover an account. It is **recommended** to provide a valid contact address using this variable.

If you want to do this globally for all containers, set `DEFAULT_EMAIL` on the **letsencrypt_nginx_proxy_companion container**.

**Please note that for each separate [ACME account](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#acme-account-keys), only the email provided as a container environment variable at the time of this account creation will be subsequently used. If you don't provide an email address when the account is created, this account will remain without a contact address even if you provide an address in the future.**

Example:

```bash
$ docker run -d nginx \
  VIRTUAL_HOST=somedomain.tld \
  LETSENCRYPT_HOST=somedomain.tld \
  LETSENCRYPT_EMAIL=contact@somedomain.tld

$ docker run -d nginx \
  VIRTUAL_HOST=anotherdomain.tld \
  LETSENCRYPT_HOST=anotherdomain.tld \
  LETSENCRYPT_EMAIL=someone@anotherdomain.tld
```

This will result in only the first address being used (contact@somedomain.tld) and it will be used for **all** future certificates issued with the default ACME account.

This incorrect behaviour is due to a misunderstanding about the way ACME handled contact address(es) when the container was changed to re-use ACME account keys ([more info there](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/510#issuecomment-463256716)) and the fact that `simp_le` is silently discarding the unused addresses. Due to this, it is highly recommended to use the [`DEFAULT_EMAIL`](#default-contact-address) environment variable to avoid unwittingly creating ACME accounts without contact addresses.

If you need to use different contact addresses, you'll need to either use different [ACME account aliases](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#multiple-account-keys-per-endpoint) or [disable ACME account keys re-utilization entirely](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#disable-account-keys-re-utilization).

**Comment by buchdag** [comment]
@jeroen-plug @linusg @almereyda @jalu14, any comment on the above ?

**Comment by jeroen-plug** [comment]
Looks clear to me.
I do notice that you recommend setting `LETSENCRYPT_EMAIL` in the first paragraph, and switch to recommending `DEFAULT_EMAIL` instead in the second last paragraph.
Maybe it's a good idea to stick with one as the recommended approach for most users, and change that in the basic usage examples as well.

**Comment by buchdag** [comment]
> I do notice that you recommend setting `LETSENCRYPT_EMAIL` in the first paragraph, and switch to recommending `DEFAULT_EMAIL` instead in the second last paragraph.

Right, I did not notice that, I'll have to rephrase it.

> Maybe it's a good idea to stick with one as the recommended approach for most users, and change that in the basic usage examples as well.

Agreed.

**Comment by linusg** [comment]
I agree with @jeroen-plug as well, looks good otherwise. I like the explanation at the end on what exactly is happening and why it's happening. Thanks!

**Comment by buchdag** [comment]
Done as of #550

**Comment by linusg** [comment]
Any idea when it will be released @buchdag? I can't wait to strip all the equal `LETSENCRYPT_EMAIL` env variables from my Docker compose file...

**Comment by buchdag** [comment]
It's been merged to master so it's already available in `latest`.
