### ISSUE TITLE
Nginx exited after restart

### ISSUE THREAD

**Issue by synopsisdevs** [JrCs/docker-letsencrypt-nginx-proxy-companion#69]
Hi, 

after first start everything is ok, but after restart containers exited with error: 
`nginx: [emerg] open() "/etc/nginx/vhost.d/default" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:41`.
I used docker-compose.yml from examples for v1: [https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v1/simple-site/docker-compose.yml](url)

Could you tell me what is wrong?

Thanks

**Comment by faultylee** [comment]
Hi, actually I'm getting the same error as well recently. I found that `default.conf` is pointing to another non existing `.conf`. Deleting it before starting again seems to resolve this issue. I've yet to dig deeper.

**Comment by deciare** [comment]
The first time the **nginx** container starts, `/etc/nginx/conf.d/default.conf` contains default configuration from the nginx image, and starts up successfully.

`/etc/nginx/vhost.d/default` is later created by **letsencrypt-nginx-proxy-companion**, and if that file exists while **docker-gen** parses the template to regenerate `/etc/nginx/conf.d/default.conf`, the following line gets added to the newly-generated server block:

```
    include /etc/nginx/vhost.d/default;
```

When **letsencrypt-nginx-proxy-companion** stops, `/etc/nginx/vhost.d/default` is removed, but the previously-generated `/etc/nginx/conf.d/default.conf` is left in place. The next time the **nginx** container is started, the `include` directive still exists, but `/etc/nginx/vhost.d/default` no longer does, so nginx fails to start.

**docker-gen** does notice when **letsencrypt-nginx-proxy-companion** is stopped, so it eventually regenerates a `/etc/nginx/conf.d/default.conf` without the include, but when both **letsencrypt-nginx-proxy-companion** and **docker-gen** are stopped in rapid succession, the regeneration doesn't have a chance to take place.

Since nginx starts fine with no `/etc/nginx/conf.d/default.conf` at all, and the file will get regenerated anyway within a few seconds of **letsencrypt-nginx-proxy-companion** stopping (if only that one container is being stopped), might it be helpful to automatically remove `/etc/nginx/conf.d/default.conf` in addition to `/etc/nginx/vhost.d/default` when **letsencrypt-nginx-proxy-companion** is stopped?

**Comment by elohmeier** [comment]
+1

**Comment by 1beb** [comment]
Same issue here. I have to delete `nginx`, `nginx-gen` before a restart (up > down > up). Please let me know if I can help with debuging. I can share my docker-compose files (edited)

**Comment by mlegenhausen** [comment]
+1

**Comment by jedwards1211** [comment]
@JrCs The fact that the `nginx` container can start outside of the control of the `nginx-gen` container seems error-prone to me.  I'd much rather see nginx (or some plugin) be able to evaluate a script to generate the config each time it runs, much like a lot of JS tools now use JS files for config instead of JSON.

**Comment by jedwards1211** [comment]
For instance: https://www.nginx.com/blog/launching-nginscript-and-looking-ahead/

**Comment by creecros** [comment]
i'm still having this issue. 

system reboot, nginx-proxy starts up with .vhost.d/default missing, let'sencrypt-companion comes back up and now all the certs disappear, i think because on restart it wants to regenerate them, however without the existing ones nginx-proxy is now running without the certs and lets encrypt fails well/known with too many requests and your down for hours after that. 

I can't figure this one out.
