### ISSUE TITLE
Self-signed for development

### ISSUE THREAD

**Issue by asmaloney** [JrCs/docker-letsencrypt-nginx-proxy-companion#8]
I have some sites I want to migrate to HTTPS, so I want to work on them locally to make sure they work before moving the live sites.

If I use this container as part of my docker infrastructure, how do I use self-signed certs for my development environment?

Can I just create them and put them in the certs directory and everything will work?  Or will this container try to check them/renew them with ACME and blow up?

(I'm relatively new to working with HTTPS and trying to understand how to work with it.)

**Comment by JrCs** [comment]
All you need to do is put your self signed certificates in the nginx certs directory.
Certs are created with this container ONLY if the webserver container defines the LETSENCRYPT_XXXX environment variables.

**Comment by asmaloney** [comment]
Just to clarify - if I don't set the env vars, this container will still see the self-signed certs in the certs directory and modify the nginx config to pick them up and use them, it just won't try to create or renew them?

**Comment by JrCs** [comment]
@asmaloney exactly

**Comment by asmaloney** [comment]
Great, thanks!  And thank you again for creating this.  Very helpful.

**Comment by kachkaev** [comment]
@JrCs could you please extend `README.md` a bit to help newcomers configure the dev environment? My app consists of a few `docker-compose.yml` files, the first of which sets up `nginx`/`docker-gen`/`letsencrypt` bundle. Other services are started later and expect the traffic to arrive from that bundle. When I'm on localhost, my root domain name is `my-project.dev`. The services I start are at `a.my-project.dev`, `b.my-project.dev`, etc. Because all the traffic is expected to go via `https` and letsencrypt fails to get the right certs, I can't open anything in the browser. Would be good to know in which folders and in what format to put these dummy certs you are mentioning.

**Comment by JrCs** [comment]
@kachkaev We don't have dummy certs. Certs are created by letsencrypt container in the nginx certs directory automatically.

**Comment by kachkaev** [comment]
@JrCs OK, thank you. I'm new to letsencrypt, so might be asking stupid questions. Given the configuration of the services I shared above, how would recommend organising the development environment?

I would like my future dockerized services `my-project.com`, `a.my-project.com` and `b.my-project.com` to stay behind `nginx` / `docker-gen` & `letsencrypt` even in development, while I play with them at `my-project.dev`, `a.my-project.dev` and `b.my-project.dev`. This means that there should be some mocking of https certs on my localhost so that I could open `.dev` domains in the browser in https mode. This will allow me to test the full stack before putting it to production.

What should I tweak to be able to use the same `dockeer-compose.yml` files in dev and prod (with different `.env`, of course)?

**Comment by JrCs** [comment]
You can't create certs for .dev domain because i don't think the root .dev domain exists.
For your dev environment you can use the .com certificates create by letsencrypt and when you connect to the .dev site allow to use an invalid certificate (a .com certificate for a .dev domain)

**Comment by kachkaev** [comment]
@JrCs this suggests that I can have a bunch of files on my laptop that represent a certificate for some domain (which is not any of my dev domains, of course). What I should do is to copy these files into `/certs/` folder that nginx picks and then rename them somehow so that they represent `a.my-project.dev` and `www.a.my-project.dev`, for instance. What is unclear to me is what files to take and where to put them. I'm happy with a warning in a browser when I access `*.dev`.

There might be a section in your readme that helps in such a case. It will provide a link to the files that represent an invalid certificate and explain where to put these files to mock a successfully generated certificate. Nginx proxy will swallow them and will enable local testing of the full stack of docker services.

Would be really good if you could help with this.

**Comment by kachkaev** [comment]
Or maybe even `docker-letsencrypt-nginx-proxy-companion` could create some fake dev-mode certificates for my domains if I pass it some flag via an ENV variable? This would be just perfect!

**Comment by JrCs** [comment]
Just add some links in the nginx cert directory. Each must be name as a .dev domain (like www.a.my-project.dev) that point to the my-project.com multidomain certificate.
Nginx will use any certs that it will find in the nginx cert directory.

But i think it must be easier to access .dev domain directly (without https) and only proxyfied https to http the .com domains with nginx

**Comment by kachkaev** [comment]
I've been trying to copy and rename different files inside `/etc/nginx/certs`, but never got to a point when they were picked by nginx.

Looks like local testing https in a multi-domain project is quite a pain and a time waster even if you are knowledgeable. You first have to get a bunch of files that represent some domain and then for each new domain manually go to `/etc/nginx/certs` and create symlinks. There's probably a need to trigger some hook after this.

An ideal solution would be just to start the container with something like `SELF_SIGNED=true` or `DUMMY_CERTS=true` or `ACME_CI_URI=dummy` to completely mock letsencrypt requests.

@asmaloney @JrCs could you please suggest some little cheat sheet on what to do to enable self-signed (or what ever dummy) certificates for the development domains?

**Comment by asmaloney** [comment]
The solution I used wasn't exactly awesome, but it got me where I needed to go.

I did this a while ago, so I hope I'm not missing steps.  I did the following:

- took **docker-letsencrypt-nginx-proxy-companion** completely out of the loop by not passing `LETSENCRYPT_HOST`
- generated a self-signed cert: `openssl req -x509 -days 365 -keyout localhost.key -out localhost.crt`
- copied the `localhost.crt`  and `localhost.key` files into my certs directory
- changed `VIRTUAL_HOST` in my run command to point to localhost: `-e "VIRTUAL_HOST=localhost"`

I only used this on one domain at a time, but I imagine for multiple domains you could generate the certs as above with `foo.local` instead og `localhost` and then just make sure your host system resolves `foo.local` properly?

**Comment by kachkaev** [comment]
Thanks @asmaloney!

Yeah, this looks a bit tedious to do apply, especially if you want to have multiple domains and use dockercompose. I'm using a combination of variables from `.env` in my `docker-compose.yml` and the configs often contain the following:

```
services:
  web:
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - LETSENCRYPT_EMAIL=admin@${ROOT_HOST}
```

My goal is to start `app1-prod.my-project.dev`, `app1-next.my-project.dev`, `app2.my-project.dev`, etc. and then re-use the same git repos and images on the server just by changing `ROOT_HOST` and some `DEV` flag in the `.env` files. Rather than testing the containers locally one by one I see a huge benefit in running the whole project together. If `letsencrypt-nginx-proxy-companion` could work in some _dummy cert mode_ on a local machine while I'm playing with `https://*.my-project.dev`, it would be awesome.

**Comment by kachkaev** [comment]
@JrCs could you please consider implementing self-signed certificates as an extra dev mode option? What is your opinion on this?

**Comment by JrCs** [comment]
@kachkaev Sorry by this companion it's only used to create signed certificate from letsencrypt, no more no less.
If you want to create self-sign certificates use another container that will use the openssl tools to create this certificates.

**Comment by kachkaev** [comment]
@JrCs that's a bit of a shame as such functionality would be useful in some dev workflows, but I understand your view. Keeping the list of features as small as possible is a great, not a bad thing!

I might do a small investigation later on how to make https available on a local machine while testing websites behind nginx reverse-proxy and docker-gen. The goal would be to exclude any manual work and minimise the difference between `docker-compose.yml` on the local machine and on the real servers. Drop your ideas here if you're in the same situation as I am!

**Comment by hadim** [comment]
That feature would be really helpful !!!

**Comment by mvigneron** [comment]
Hello @kachkaev,

I am in the same situation. I would like to have https available in developpement environnement. did you manage to do that ? 

Thanks for your help

**Comment by buchdag** [comment]
```
docker exec -it your-le-companion-container \
    openssl req -x509 \
    -newkey rsa:4096 \
    -nodes \
    -days 365 \
    -subj '/CN=yourdomain.tld'  \  
    -keyout /etc/nginx/certs/yourdomain.tld.key \
    -out /etc/nginx/certs/yourdomain.tld.crt

docker exec nginx-proxy nginx -s reload
```

**Comment by ShaneOH** [comment]
Thanks @wvengen for getting me started on that. Here's an example with .env support using sed for anyone else looking into this:

```
export $(egrep -v '^#' .env | xargs)

DOMAINS=`cat ./docker-compose.yml | sed 's/,/\n/g; s/^.*LETSENCRYPT_HOST=\(.*\)/\1/p;d'`

for domain in ${DOMAINS}; do
  if [[ ${domain} == \$* ]]; then
    domain=$(echo $domain | sed -e 's/^${//' -e 's/}$//')
    domain=${!domain}
  fi

  openssl req -x509 \
    -newkey rsa:4096 \
    -sha256 \
    -nodes \
    -days 365 \
    -subj "/CN=${domain}"  \
    -keyout "./certs/${domain}.key" \
    -out "./certs/${domain}.crt"
done
```
