### ISSUE TITLE
Cannot set timezone

### ISSUE THREAD

**Issue by yannisc** [JrCs/docker-letsencrypt-nginx-proxy-companion#99]
I start the container with the -e TZ="Europe/Athens" environment variable in order to set the timezone and see logs in my timezone, but it seems that this env variable is not honored. Logs keep showing in UTC.

**Comment by ryneeverett** [comment]
Why would you expect it to be honored?

**Comment by yannisc** [comment]
It works like these on other images, so I thought this is kind of standard. If not, excuse me for asking.

**Comment by ryneeverett** [comment]
I'm not familiar with that convention but that doesn't mean it doesn't exist. I doubt it will be implemented here though because it doesn't seem to be implemented in the nginx-proxy or nginx images which are, in a sense, "upstream".

Furthermore, storing localized times strikes me as almost never a good idea. Best to store everything in utc and localize it in the representation layer -- in this case presumably a log aggregator.

**Comment by yannisc** [comment]
That makes sense. Thank you for your response.

**Comment by tinsjourney** [comment]
If your host is configured to the good time zone you can just mount /etc/localtime in your container, using "-v /etc/localtime:/etc/localtime:ro"
